// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using JsonBackend.Model;
//
//    var person = Person.FromJson(jsonString);

using System;
using System.Collections.Generic;

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;

namespace JsonBackend.Model;

public partial class Person {
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("Name")]
    public string Name { get; set; }

    [JsonPropertyName("LastSeen")]
    public string LastSeen { get; set; }

    [JsonPropertyName("SocialCredit")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long SocialCredit { get; set; }
    
    public string ToJson() => JsonSerializer.Serialize(this);
}

public partial class Person {
    public static List<Person> FromJson(string json) => JsonSerializer.Deserialize<List<Person>>(json, JsonBackend.Model.Converter.Settings);
}

public static class Serialize {
    public static string ToJson(this List<Person> self) => JsonSerializer.Serialize(self, JsonBackend.Model.Converter.Settings);
}

internal static class Converter {
    public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General) { };
}

internal class ParseStringConverter : JsonConverter<long>
{
    public override bool CanConvert(Type t) => t == typeof(long);

    public override long Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value.ToString(), options);
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}
